version: 2
companion_workflows:
  - .github/workflows/entry.yml
  - .github/workflows/lint.yml
  - .github/workflows/test.yml
  - .github/workflows/build.yml
  - .github/workflows/release.yml
pipelines:
  ci:
    stages:
      - id: lint
        workflow: .github/workflows/lint.yml
      
      - id: test
        workflow: .github/workflows/test.yml
        needs:
          - lint

      - id: build
        workflow: .github/workflows/build.yml
        needs:
          - test

      - id: release
        workflow: .github/workflows/release.yml
        needs:
          - build
